### PR TITLE
Available entities mode

### PR DESCRIPTION
**Pull request by albaintor**
As discussed : 
- Available entities only are managed by the HA component

### CODE REVIEW

**Review by zehnm — CHANGES_REQUESTED** [review]
Thanks, looks goot to me 👍 
Please format the sources with `cargo fmt` so that the checks pass and I will merge the PR.

**Comment by albaintor** [comment]
Ok done !

**Review by zehnm — CHANGES_REQUESTED** [review]
`Cargo.lock` needs to be reverted. Updated dependencies break the cross compilation build.

The issue is an older libc version in the cross compile toolchain of the device.
Even though Cargo dependencies work pretty well, the libc handling leaves a lot to be desired. Patch updates of certain crates pull in a newer libc version and everything breaks :-(

I have to update the SDK toolchain to resolve this issue. Until then no crate updates (or manual downgrades with version pinning as done in the past).

Sorry about that!

**Comment by albaintor** [comment]
I tried to revert but I have compilation errors with the reverted file, and besides the intg-hass library rolls back to 0.10 instead of 0.11. I don't understand what's going on ?

**Review by zehnm — CHANGES_REQUESTED** [review]
Looks like a bit too much has been reverted. Just the `Cargo.lock` should have been reverted to the state in the main branch.

Now CHANGELOG.md and driver.json are in an older state.

**Comment by albaintor** [comment]
Done, I reverted the git release instead the file sorry for that

**Review by zehnm — APPROVED** [review]
No worries, it's good now!
I should be able to still include it in the next beta release.

**Pull request merged**
